import { DM_Sans, Lora } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import Header from "@/components/ui/Header";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "500"],
  style: ["normal", "italic"],
  variable: "--font-serif",
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Prept",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
  <html lang="en" className="dark" suppressHydrationWarning>
    <body className={`${lora.variable} ${dmSans.variable} font-sans`}>
      <Header />
      <main className="min-h-screen">{children}</main>
    </body>
  </html>
</ClerkProvider>
  );
}